---
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: "{{ state }}"
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ key_name }}"
      wait: yes
      flavor: "{{ flavor_name }}"
      auto_floating_ip: "{{ auto_ip }}"
      network: "{{ network_name }}"
